import fs from 'fs';
let content = fs.readFileSync('src/App.tsx', 'utf-8');

const replacements = {
  "Pist & Kurulum": "Track & Setup",
  "Lastik Analiz": "Tyre Analysis",
  "Motor Çıktısı": "Strategy Engine",
  "Eğitim": "Calibration",
  "Uygulama Menüsü": "App Menu",
  "Ayarlar": "Settings",
  "Hesap & Senkronizasyon": "Account & Sync",
  "Uygulama Ayarları": "App Settings",
  "Tema, dil seçenekleri ve bildirim ayarları": "Theme, language and notifications",
  "Verilerinizi buluta yedekleyin": "Backup and sync data to cloud",
  "Görünüm Ayarları": "Appearance Settings",
  "Açık Tema": "Light Theme",
  "Koyu Tema": "Dark Theme",
  "Sistem": "System",
  "Tercihler": "Preferences",
  "İsteğe bağlı uygulama davranışları": "Optional app behaviors",
  "Uygulama İçi Bildirimler": "In-App Notifications",
  "Bölüm geçişleri veya uyarılar": "Alerts for transitions",
  "Pit zamanı ve aşınma uyarıları.": "Pit time and wear alerts.",
  "Otomatik Çeviri (Google Translate)": "Auto Translate (Google)",
  "Yabancı dilde görüntülemek için": "Display in other languages",
  "Tüm metinleri otomatik çevirmeyi etkinleştir.": "Enable automatic text translation",
  "Akıllı Senkronizasyon": "Smart Sync",
  "Cloud veri transferini minimize eder": "Minimize cloud data transfer",
  "Hesaplamalarda bulut tasarruf modu.": "Cloud save mode for calculations.",
  "Senkronizasyon Modülü": "Sync Module",
  "Pilot ve araç verilerinizi": "Backup your driver and car data to use across devices.",
  "Devam etmek için Google hesabınızla giriş yapın": "Sign in with Google to continue.",
  "Google ile Giriş Yap": "Sign in with Google",
  "GPRO Oyuncusu": "GPRO Player",
  "Çıkış": "Logout",
  "Mevcut Veriyi Buluta Kaydet": "Save Data to Cloud",
  "Buluttan Cihaza Yükle \\(İndir\\)": "Load from Cloud (Download)",
  "Pist & Koşullar": "Track & Conditions",
  "Güncel Takvimden Çek": "Fetch Live Calendar",
  "Pist Seçimi": "Track Selection",
  "Tur Sayısı": "Laps",
  "Yarışın atılacak toplam tur sayısı.": "Total number of laps.",
  "Aşınma Seviyesi": "Wear Severity",
  "Yakıt Yakımı": "Fuel Burn",
  "Base Pit Süresi \\(sn\\)": "Base Pit Time (s)",
  "Pite girip çıkmanın yakıt alımı hariç": "Time lost in pitlane (excluding refuel).",
  "Hava Durumu": "Weather",
  "Mak \\(°C\\)": "Max (°C)",
  "Min \\(°C\\)": "Min (°C)",
  "Yağmur Olasılıkları \\(%\\)": "Rain Probabilities (%)",
  "Sıralama \\(Q1-Q2\\) ve yarış içi \\(30'ar dakikalık paylar\\) ihtimallerini buradan değiştirebilirsiniz. %0 ise kuru zemin hesabı yapılır.": "Configure qualifying and race rain probabilities.",
  "Akıllı Görüntü Okuyucu \\(SS\\)": "Smart Screenshot Reader",
  "Prototip": "Prototype",
  "Tarayıcı düzeyinde çalışır \\(Offline\\), resim göndermez. Sayı olan bilgileri tahmin eder, küçük hatalar yapabilir.": "Runs in browser offline. Guesses number values.",
  "Oyun verilerini yazmakla uğraşmayın. Ekran görüntüsünü \\(SS\\) sisteme yükleyin, çevre metinlerine göre değerleri tespit edelim. Ne kadar dar ve net kırparsanız doğruluk o kadar artar.": "Upload a screenshot for auto data detection. Clip tightly around numbers for better accuracy.",
  "📸 Fotoğraf Seç ve Oku": "📷 Select & Read Screenshot",
  "Taranıyor, lütfen bekleyin...": "Scanning, please wait...",
  "İşleniyor": "Processing",
  "Algılanan Veriler": "Detected Data",
  "Min Sıcaklık:": "Min Temp:",
  "Max Sıcaklık:": "Max Temp:",
  "Konsantrasyon:": "Focus:",
  "Dayanıklılık:": "Stamina:",
  "Deneyim:": "Experience:",
  "Pilot Agresifliği \\(Risk\\)": "Driver Aggressiveness (Risk)",
  "Onayla ve Oyuna İşle": "Confirm & Apply",
  "Araç ve Pilot Verileri \\(Dinamik\\)": "Car & Driver Data (Dynamic)",
  "Pilot yetenekleri, araç markası gibi etkenler aşınmayı ciddi etkiler.": "Driver skills and chassis impact base wear.",
  "Değerleri varsayılana sıfırla.": "Reset values to default.",
  "Lastik Markası": "Tyre Supplier",
  "Tüm markaların erime hızları farklıdır. Fabrika ayarlarına \\('Pipirelli'\\) dönmek için butona basın.": "Different brands have different wear rates.",
  "Temel Yakıt Yakımı": "Base Fuel per Lap",
  "Aracınızın standart tur başına yakıt miktarı": "Standard fuel burn per lap.",
  "Lastik Aşınma Çarpanı": "Tyre Wear Multiplier",
  "Varsayılan:": "Default:",
  "Pilot & Araç": "Driver & Car",
  "Tüm erime hesaplarına eklenecek gizli risk çarpanı. Varsayılana \\(1.0x\\) dönmek için bas.": "Hidden risk multiplier added to wear calculations.",
  "Temel Oyun Motoru Sabitleri": "Engine Constants",
  "Yakıt Ağırlığı Ceza Katsayısı": "Fuel Weight Penalty Coefficient",
  "Yakıt İkmal Hızı": "Refuel Rate",
  "Hesaplama Ayarları \\(Gelişmiş\\)": "Calculation Settings (Advanced)",
  "Pilot Agresifliği \\(Risk\\)": "Driver Aggression",
  "Gerçek Zamanlı": "Live Mode",
  "Bulutta kayıt bulunamadı.": "No cloud save found.",
  "Başarıyla yüklendi!": "Loaded successfully!",
  "Yükleniyor...": "Loading...",
  "Bulut bağlantısı aktif.": "Cloud connection active.",
  "Buluta kaydediliyor...": "Saving to cloud...",
  "Başarıyla kaydedildi!": "Saved successfully!"
};

for (const [tr, en] of Object.entries(replacements)) {
  content = content.replace(new RegExp(tr, 'g'), en);
}

fs.writeFileSync('src/App.tsx', content);
console.log('App.tsx strings translated.');
