import { Track, TyreCompound } from "./types.ts";

// Severity multipliers for Fuel and Wear
export const SEVERITY_MULTIPLIERS = {
  "Very Low": 0.75,
  Low: 0.88,
  Medium: 1.0,
  High: 1.15,
  "Very High": 1.3,
};

// Relative pace difference per compound (seconds per lap difference from XS)
// XS is the fastest, XH the slowest.
export const COMPOUND_PACE: Record<TyreCompound, number> = {
  XS: 0.0,
  S: 0.5,
  M: 1.2,
  H: 2.0,
  Rain: 5.0, // Highly variable depending on actual water
};

// Base Wear Rate per lap (%) at optimal temperature (around 20-25C)
export const COMPOUND_WEAR_RATE: Record<TyreCompound, number> = {
  XS: 4.5,
  S: 3.2,
  M: 2.1,
  H: 1.5,
  Rain: 2.5,
};

// Ideal operating temperature per compound. Above this, wear increases significantly.
export const COMPOUND_IDEAL_TEMP: Record<TyreCompound, number> = {
  XS: 10,
  S: 15,
  M: 22,
  H: 28,
  Rain: 15,
};

// Full display names for UI
export const COMPOUND_FULL_NAMES: Record<TyreCompound, string> = {
  XS: "Extra Soft",
  S: "Soft",
  M: "Medium",
  H: "Hard",
  Rain: "Rain",
};

// Some standard GPRO tracks (A subset for the tool to demonstrate)
export const TRACK_DATABASE: Track[] = [
  {
    id: "montreal",
    name: "Montreal",
    laps: 70,
    distance: 305.2,
    fuelSeverity: "High",
    wearSeverity: "Medium",
    pitTimeBase: 19.5,
  },
  {
    id: "melbourne",
    name: "Melbourne",
    laps: 58,
    distance: 307.5,
    fuelSeverity: "High",
    wearSeverity: "Low",
    pitTimeBase: 21.0,
  },
  {
    id: "sepang",
    name: "Sepang",
    laps: 56,
    distance: 310.4,
    fuelSeverity: "Medium",
    wearSeverity: "High",
    pitTimeBase: 22.5,
  },
  {
    id: "bahrain",
    name: "Sakhir",
    laps: 57,
    distance: 308.2,
    fuelSeverity: "High",
    wearSeverity: "High",
    pitTimeBase: 23.0,
  },
  {
    id: "catalunya",
    name: "Barcelona",
    laps: 66,
    distance: 307.1,
    fuelSeverity: "Medium",
    wearSeverity: "High",
    pitTimeBase: 21.5,
  },
  {
    id: "monaco",
    name: "Monaco",
    laps: 78,
    distance: 260.2,
    fuelSeverity: "Low",
    wearSeverity: "Very Low",
    pitTimeBase: 23.5,
  },
  {
    id: "silverstone",
    name: "Silverstone",
    laps: 52,
    distance: 306.1,
    fuelSeverity: "High",
    wearSeverity: "Very High",
    pitTimeBase: 20.0,
  },
  {
    id: "estoril",
    name: "Estoril",
    laps: 71,
    distance: 309.7,
    fuelSeverity: "Medium",
    wearSeverity: "Medium",
    pitTimeBase: 22.0,
  },
  {
    id: "bremgarten",
    name: "Bremgarten",
    laps: 42,
    distance: 305.8,
    fuelSeverity: "High",
    wearSeverity: "Medium",
    pitTimeBase: 22.0,
  },
  {
    id: "zandvoort",
    name: "Zandvoort",
    laps: 72,
    distance: 306.6,
    fuelSeverity: "Medium",
    wearSeverity: "Medium",
    pitTimeBase: 22.0,
  },
  {
    id: "zolder",
    name: "Zolder",
    laps: 70,
    distance: 298.3,
    fuelSeverity: "Medium",
    wearSeverity: "High",
    pitTimeBase: 22.0,
  },
  {
    id: "anderstorp",
    name: "Anderstorp",
    laps: 80,
    distance: 322.2,
    fuelSeverity: "Medium",
    wearSeverity: "Low",
    pitTimeBase: 22.0,
  },
  {
    id: "sochi",
    name: "Sochi",
    laps: 53,
    distance: 309.7,
    fuelSeverity: "High",
    wearSeverity: "Medium",
    pitTimeBase: 24.0,
  },
  {
    id: "monza",
    name: "Monza",
    laps: 53,
    distance: 306.7,
    fuelSeverity: "Very High",
    wearSeverity: "Low",
    pitTimeBase: 24.0,
  },
  {
    id: "ahvenisto",
    name: "Ahvenisto",
    laps: 70,
    distance: 300,
    fuelSeverity: "Medium",
    wearSeverity: "Medium",
    pitTimeBase: 22.0,
  },
  {
    id: "magny_cours",
    name: "Magny Cours",
    laps: 70,
    distance: 308,
    fuelSeverity: "Medium",
    wearSeverity: "High",
    pitTimeBase: 22.0,
  },
  {
    id: "poznan",
    name: "Poznan",
    laps: 73,
    distance: 305,
    fuelSeverity: "Medium",
    wearSeverity: "Medium",
    pitTimeBase: 22.0,
  },
  {
    id: "spielberg",
    name: "A1-Ring",
    laps: 71,
    distance: 306,
    fuelSeverity: "High",
    wearSeverity: "Medium",
    pitTimeBase: 22.0,
  },
  {
    id: "jyllands",
    name: "Jyllands-Ringen",
    laps: 70,
    distance: 300,
    fuelSeverity: "Medium",
    wearSeverity: "Medium",
    pitTimeBase: 22.0,
  },
  {
    id: "buenos_aires",
    name: "Buenos Aires",
    laps: 72,
    distance: 306,
    fuelSeverity: "Medium",
    wearSeverity: "Low",
    pitTimeBase: 22.0,
  },
  {
    id: "austin",
    name: "Austin",
    laps: 56,
    distance: 308,
    fuelSeverity: "High",
    wearSeverity: "High",
    pitTimeBase: 22.0,
  },
  {
    id: "spa",
    name: "Spa",
    laps: 44,
    distance: 308,
    fuelSeverity: "High",
    wearSeverity: "High",
    pitTimeBase: 22.0,
  },
  {
    id: "kaunas",
    name: "Kaunas",
    laps: 60,
    distance: 300,
    fuelSeverity: "Medium",
    wearSeverity: "Medium",
    pitTimeBase: 22.0,
  },
  {
    id: "hungaroring",
    name: "Hungaroring",
    laps: 70,
    distance: 306,
    fuelSeverity: "Medium",
    wearSeverity: "High",
    pitTimeBase: 22.0,
  },
  {
    id: "lusail",
    name: "Losail",
    laps: 57,
    distance: 306,
    fuelSeverity: "High",
    wearSeverity: "High",
    pitTimeBase: 22.0,
  },
  {
    id: "delhi",
    name: "New Delhi",
    laps: 60,
    distance: 308,
    fuelSeverity: "Medium",
    wearSeverity: "Low",
    pitTimeBase: 22.0,
  },
  {
    id: "yas_marina",
    name: "Yas Marina",
    laps: 58,
    distance: 305,
    fuelSeverity: "High",
    wearSeverity: "Medium",
    pitTimeBase: 22.0,
  },
  {
    id: "brno",
    name: "Brno",
    laps: 56,
    distance: 302.5,
    fuelSeverity: "Medium",
    wearSeverity: "Medium",
    pitTimeBase: 22.0,
  },
  {
    id: "valencia",
    name: "Valencia",
    laps: 57,
    distance: 308.9,
    fuelSeverity: "Medium",
    wearSeverity: "Medium",
    pitTimeBase: 22.0,
  },
  {
    id: "indianapolis",
    name: "Indianapolis",
    laps: 73,
    distance: 306.0,
    fuelSeverity: "High",
    wearSeverity: "Low",
    pitTimeBase: 22.0,
  },
  {
    id: "mexico_city",
    name: "Mexico City",
    laps: 71,
    distance: 305.4,
    fuelSeverity: "Medium",
    wearSeverity: "Low",
    pitTimeBase: 22.0,
  },
  {
    id: "brasilia",
    name: "Brasilia",
    laps: 56,
    distance: 306.2,
    fuelSeverity: "Medium",
    wearSeverity: "Medium",
    pitTimeBase: 22.0,
  },
  {
    id: "baku",
    name: "Baku City",
    laps: 51,
    distance: 306.0,
    fuelSeverity: "Medium",
    wearSeverity: "Medium",
    pitTimeBase: 22.0,
  },
  {
    id: "shanghai",
    name: "Shanghai",
    laps: 56,
    distance: 305.1,
    fuelSeverity: "High",
    wearSeverity: "Medium",
    pitTimeBase: 22.0,
  },
  {
    id: "fuji",
    name: "Fuji",
    laps: 67,
    distance: 305.7,
    fuelSeverity: "High",
    wearSeverity: "High",
    pitTimeBase: 22.0,
  },
  {
    id: "singapore",
    name: "Singapore",
    laps: 61,
    distance: 308.8,
    fuelSeverity: "Medium",
    wearSeverity: "High",
    pitTimeBase: 24.0,
  },
  {
    id: "custom",
    name: "Custom Track",
    laps: 60,
    distance: 300,
    fuelSeverity: "Medium",
    wearSeverity: "Medium",
    pitTimeBase: 22.0,
  },
];
